apiVersion: backstage.io/v1alpha1
kind: Component
metadata:  
  name: test-github
  description: |
        Repositorio ejemplo backstage catalog. Prueba github docs
  tags: ["test", "job", "release", "prueba", "test2"]
  links:
    - url: https://github.com/sergiopintoviewnext/varios
      title: Link-Github-Reposirotio
      icon: github
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: test
  system: test-local
  owner: VIEWNEXT_TORRE_DE_CONTROL
  lifecycle: release
