site_name: 'varios - prueba backstage'
site_description: "Documentacion prueba para backstage"
nav:
  - README: index.md
plugins:
  - techdocs-core
theme:
  name: mkdocs
  highlightjs: true
  nav_style: dark
  hljs_languages:
    - yaml
    - rust
